name: Check for typos

on:
  pull_request:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install npm
        uses: actions/setup-node@v3

      - name: Install write-good
        run: npm install -g write-good

      - name: Run write-good for all *.md filse
        run: write-good *.md
